### ISSUE TITLE
Regex not working in RIDE?

### ISSUE THREAD

**Issue by Awcmon** [RantLang/RIDE#3]
For example if I have code like

    [case:title]{Operation <adj?//(^b)//> <noun?//(^b)//>} \n

I just get an error that says "Expected regex" where the first forward slash is.

Not sure if this is known or not, or my code is just wrong (It works on RantBox though).

**Comment by TheBerkin** [comment]
The regex syntax has changed in the new version of Rant, and uses ` instead of //. The documentation has not yet been rewritten to reflect this. I apologize.
